### ISSUE TITLE
Phpstorm seems confused over map function return type

### ISSUE THREAD

**Issue by ThomasCarbon** [jolicode/automapper#133]
It seems that Phpstorm doesnt understand this line in `AutomapperInterface.php`

`Returns: ($target is class-string|Target ? Target|null : array<mixed>|null)`

I don't know if anything is possible about it or if it's something i did wrong on my side.

See screenshot bellow 

![Screenshot from 2024-05-14 14-30-13](https://github.com/jolicode/automapper/assets/116898217/6c0d5184-db8f-4cba-a0ff-7754b3d47ef3)

**Comment by lyrixx** [comment]
For the record, the issue is not with the interface as said by @ThomasCarbon 

https://phpstan.org/r/5626d4c8-ba69-47fe-bea3-d75ede7ba5d6

and it works on vscode too

![image](https://github.com/jolicode/automapper/assets/408368/d9701ff5-c8e8-4944-8f0a-abc968c8a2a9)

**Comment by ThomasCarbon** [comment]
It fixed it in my case. Thanks guys.
