### ISSUE TITLE
How to keep indexes in array when using AutoMapper ?

### ISSUE THREAD

**Issue by Korbeil** [jolicode/automapper#157]
I have the following property:
```php
public array $descriptionList = [];
```

Here is the generated code:
```php
if (null !== ($context['groups'] ?? array()) && array_intersect($context['groups'] ?? array(), array('crawl_url/clickhouse', 'crawl_url/read'))) {
  $values = array();
  foreach ($value->descriptionList as $key => $value_16) {
    $values[] = $value_16;
  }
  $result['descriptionList'] = $values;
}
```

How could we keep array indexes ?

**Comment by joelwurtz** [comment]
`/** @var array<string, string> */`?

Basically we keep key if the type we fetch have a type for the collection key 

cf https://github.com/jolicode/automapper/blob/main/src/Transformer/ArrayTransformerFactory.php#L46
