### ISSUE TITLE
Multiple MapFrom/MapTop with context

### ISSUE THREAD

**Issue by davidnurdin** [jolicode/automapper#159]
if you add multiple MapFrom with different "if", 
only one work.

`#[Mapper\MapFrom(source: "array", transformer: "source['name']['language']", if: 'source["name"] != null and (context["isWrite"] ?? false) == false')]
    #[Mapper\MapFrom(source: "array", property: "name", if: '(context["isWrite"] ?? false) == true')]
    private ?string $name = null;`

![image](https://github.com/jolicode/automapper/assets/50957749/57f11575-964b-4fc8-a6ce-c615ecf7010e)

it is normal ?

**Comment by davidnurdin** [comment]
I've create a P.R : https://github.com/jolicode/automapper/pull/160

**Comment by joelwurtz** [comment]
I'm closing this, don't hesitate to reopen it if it's not clear
