### ISSUE TITLE
[Feature] introduce attribute `#[AutoMapper\Ignore]`

### ISSUE THREAD

**Issue by nikophil** [jolicode/automapper#16]
presently, the only way to ignore a property is to use serializer's `#[Ignore]` attribute (or to use automapper context's `IGNORED_ATTRIBUTES`, but this forces to rely on properties names, and cannot be used in as a generic mechanism)

Myabe we could then introduce its own ignore attribute for the automapper?

**Comment by joelwurtz** [comment]
Fix by https://github.com/jolicode/automapper/pull/59
