### ISSUE TITLE
Feature: Inheritance support

### ISSUE THREAD

**Issue by priyadi** [jolicode/automapper#29]
Synopsis:

```php
abstract class Animal {}
class Dog extends Animal {}
class Cat extends Animal {}
class Fish extends Animal {}

abstract class AnimalDto {}
class DogDto extends AnimalDto {}
class CatDto extends AnimalDto {}
class FishDto extends AnimalDto {}

$dog = new Dog();
$cat = new Cat();
$fish = new Fish();

$dogDto = $autoMapper->map($dog, AnimalDto::class);   
$catDto = $autoMapper->map($cat, AnimalDto::class);   
$fishDto = $autoMapper->map($fish, AnimalDto::class);

$dog = $autoMapper->map($dogDto, Animal::class);
$cat = $autoMapper->map($catDto, Animal::class);
$fish = $autoMapper->map($fishDto, Animal::class);
```

My proposal for attaching metadata using attribute:

```php
#[InheritanceMapping([
    Dog::class => DogDto::class,
    Cat::class => CatDto::class,
    Fish::class => FishDto::class,
])]
abstract class AnimalDto {}
```

Logic:

* If the destination class has the `InheritanceMapping` attribute, then the mapper uses it directly
* If the destination class is abstract, look for the `InheritanceMapping` attribute in the parents of the source class, starting from the immediate parent. If found, `array_flip()` the mapping and use it.

**Comment by joelwurtz** [comment]
We do provide Inheritance Mapping from the `Symfony\Component\Serializer\Annotation\DiscriminatorMap` attribute but we are tied to symfony/serializer for this ATM

Do we want to support this without serializer poke @nikophil @Korbeil ?

If yes then we need to provide our own attribute that does this job (and add extra metadata as well)
If no we can close this

**Comment by Korbeil** [comment]
Since it's supported with Serializer attribute I would say this should be enough

**Comment by nikophil** [comment]
I kinda agree, unless the goal is to go away from serializer

**Comment by Korbeil** [comment]
Since we all agree, let's close the issue
