### ISSUE TITLE
[AutoMapper] `MappingExtractor::getWriteMutator()` returns null if property is writable

### ISSUE THREAD

**Issue by Korbeil** [jolicode/automapper#3]
Original issue: https://github.com/janephp/janephp/issues/666
Reported by: @ihmels

**Jane version(s) affected**: 7.3.1

**Description**  
If no WriteMutator can be determined via `MappingExtractor::getWriteMutator()`, but the property is writable according to `PropertyInfoExtractorInterface::isWriteable()`, an error occurs in line 73 of `SourceTargetMappingExtractor`, because `$targetMutatorConstruct` is not checked for `null`.

**How to reproduce**  

In the following code snippet there is the property `Attribute::$values` and the corresponding setter `Attribute::setValues()` (actually this should be called "setValue", but I made a typo).

The `PropertyInfoExtractorInterface` finds out with the `ReflectionExtractor` that `AttributeValue`s can be added with `addValues()`, so `PropertyInfoExtractorInterface:isWriteable()` returns true, but `MappingExtractor::getWriteMutator()` return `null`.

```php
class Attribute
{
    private Collection $values;

    public function __construct()
    {
        $this->values = new ArrayCollection();
    }

    /**
     * @return Collection<int, AttributeValue>
     */
    public function getValues(): Collection
    {
        return $this->values;
    }

    public function addValues(AttributeValue $values): void
    {
        if (!$this->values->contains($values)) {
            $this->values->add($values);
            $values->setAttribute($this);
        }
    }

    public function removeValues(AttributeValue $values): void
    {
        if ($this->values->removeElement($values)) {
            // set the owning side to null (unless already changed)
            if ($values->getAttribute() === $this) {
                $values->setAttribute(null);
            }
        }
    }
}

class AttributeValue {
    // ...
}
```

**Comment by joelwurtz** [comment]
This has been fixed with te refactor i think, not sure when, but didn't achieve to reproduce this error, i'm closing this
