### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by nikophil** [jolicode/automapper#39]
We could implement a debug mode for the automapper, here are some ideas:
- simple: some verbose logs in a monolog channel
- more sophisticated: a cli command which would print metadata and transformer used for a given class

**Comment by joelwurtz** [comment]
Don't like the monolog way, would prefer the cli

**Comment by Korbeil** [comment]
I mean, that's the same, it's just you output that Monolog channel in CLI but Monolog will allow you way more flexibility

**Comment by joelwurtz** [comment]
I think we should do something like this :

Optionnaly pass a `DebugMapper` object when building a mapper. When this object is passed it will store what and why a property was mapped (no target type / no transformer / not readeable / etc ....)

Then we can use this object in a cli / symfony profiler / or even throw a custom exception with it if we want a "strict" mapper (all properties should be mapped if it's strict)
