### ISSUE TITLE
CustomTransformers not supported in Symfony

### ISSUE THREAD

**Issue by mislavjakopovic** [jolicode/automapper#41]
Hello guys,

I'm currently blocked from using this library properly in a Symfony application.

From documentation: https://jolicode.github.io/automapper/#/?id=map-manually-a-whole-object
> In order to customize the mapping of a whole object, you can leverage `AutoMapper\Transformer\CustomTransformer\CustomModelTransformerInterface.`

Even though the code for custom transformers is in a `main` branch, it still doesn't work when doing normal installation as it was implemented after latest release `8.1.0`. 

And since my project directly depends on `automapper-bundle` I cannot just Composer override automapper package version to `dev-main` .

It would be awesome if we could have a new version with this feature out.

Thanks

**Comment by joelwurtz** [comment]
Starting from 8.2.0 there is this feature, so you can update to use it, we will certainly make something in the bundle to make it work properly in the mean time it can be overriden by a custom extension in the DIC
