### ISSUE TITLE
bug: problem when getter type is different from property type

### ISSUE THREAD

**Issue by nikophil** [jolicode/automapper#5]
**Description**  
when using `#[MapToAttribute]`, when the getter type is different from the property type, the automapper guesses the type from the property, although it should guess it from the getter's return type

**How to reproduce**  
```php
class SomeClass
{
	public function __construct(private SomeEnum $enum){}

    public function getEnum(#[MapToAttribute('foo) string $foo]): string
    {
		return "{$foo}-{$this->enum->value}";
	}
}

$automapper->map(new SomeClass(SomeEnum::FOO, 'array'));
```
this code produces an error, because the generated mapper thinks `SomeClass::getEnum()` will return an enum

**Possible Solution**  
don't know yet, need to dig into the generator

**Comment by joelwurtz** [comment]
Fixed in #77
