### ISSUE TITLE
PHP Parser version

### ISSUE THREAD

**Issue by twisted1919** [jolicode/automapper#51]
Currently getting:
```
- jolicode/automapper[8.0.0, ..., 8.2.0] require nikic/php-parser ^4.0 -> found nikic/php-parser[v4.0.0, ..., v4.18.0] but the package is fixed to v5.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

```

Using `nikic/php-parser ^4.0 || ^5.0` in your dep tree would fix this.

**Comment by joelwurtz** [comment]
There is a PR for that : https://github.com/jolicode/automapper/pull/36

So it's not just a version change, works need to be done to support this new version, but this is definitely one of our priority

**Comment by twisted1919** [comment]
Thank you, I see the PR now, I checked previously but for some reason I missed it, my bad. I am closing this, best.

**Comment by joelwurtz** [comment]
There is a new version `8.2.1` that now support php-parser 5.0
